project:
  type: website
  output-dir: docs

website:
  favicon: media/favicon.png
  navbar:
    title: "Olivia Vruwink"
    logo: media/brain.png
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Vruwink_Olivia_CV_20250208.pdf
        text: CV 
      - icon: github
        href: https://github.com/oliviavruwink
      - icon: envelope
        href: mailto:vruwi005@umn.edu
  page-footer:
    right: © Copyright 2025, Olivia Vruwink

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full

editor: source

