project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Olivia Vruwink"
    favicon: favicon.png
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Vruwink_Olivia_CV_20240617.pdf
        text: CV 
  page-footer:
    right: © Copyright 2024, Olivia Vruwink

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full

editor: source

