project:
  type: website
  output-dir: docs
  resources:
    - media/Vruwink_Olivia_CV_Website_20260806.pdf

website:
  favicon: media/favicon.png
  navbar:
    title: "Olivia Vruwink"
    logo: media/brain.png
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - icon: github
        href: https://github.com/oliviavruwink

  page-footer:
    right: © Copyright 2026, Olivia Vruwink

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full

editor: source

